project_id = "yvlvxppigamtbbisyoln"

[functions.hmrc]
verify_jwt = false

[functions.companies-house]
verify_jwt = false

[functions.ai-categorise]
verify_jwt = false

[functions.gocardless]
verify_jwt = false

[functions.receipt-ocr]
verify_jwt = false

[functions.open-banking]
verify_jwt = false