/**
 * Single source of truth for all permission modules and actions.
 * Drives: UI permission grid, backend enforcement, seed presets, audit checks.
 */
export const PERMISSION_CATALOG: Record<string, string[]> = {
  clients: ["view", "edit", "delete", "bypassAssignment", "all"],
  tasks: ["view", "edit", "approve", "delete", "assign"],
  documents: ["view", "upload", "delete", "export"],
  ledger: ["view", "edit", "lock_period", "export"],
  vat: ["view", "prepare", "submit", "approve", "export"],
  payroll: ["view", "run", "submit_rti", "approve", "export"],
  payslips: ["view", "download"],
  accounts: ["view", "prepare", "submit", "export"],
  secretarial: ["view", "edit", "approve", "submit", "export", "registers", "filings", "authcode"],
  incorporations: ["view", "create", "edit", "approve", "submit", "validate", "pay"],
  aml: ["view", "edit", "approve", "override", "export"],
  billing: ["view", "edit", "collect", "refund", "pay", "export"],
  integrations: ["view", "edit"],
  reports: ["view", "export"],
  settings: ["view", "edit"],
  automations: ["view", "edit"],
  notifications: ["view", "edit", "send"],
  submissions: ["view", "retry", "cancel"],
  templates: ["view", "edit", "preview"],
  messages: ["view", "reply", "assign", "internal"],
  onboarding: ["view", "edit", "go_live"],
  ocr: ["view", "approve", "reject"],
  portal: ["view", "upload", "messages", "bookkeeping_approve"],
  client_portal: ["view"],
  employee_portal: ["view"],
  mobile: ["sync", "upload"],
};

/** Human-readable module labels for the UI grid */
export const MODULE_LABELS: Record<string, string> = {
  clients: "Clients",
  tasks: "Tasks",
  documents: "Documents",
  ledger: "Ledger / Bookkeeping",
  vat: "VAT (MTD)",
  payroll: "Payroll (RTI)",
  payslips: "Payslips",
  accounts: "Accounts Production",
  secretarial: "Company Secretarial",
  incorporations: "Incorporations",
  aml: "AML / KYC",
  billing: "Billing & Collections",
  integrations: "Integrations",
  reports: "Reports",
  settings: "Settings",
  automations: "Automations",
  notifications: "Notifications",
  submissions: "Submissions",
  templates: "Email Templates",
  messages: "Messages",
  onboarding: "Client Onboarding",
  ocr: "Receipt OCR",
  portal: "Client Portal Access",
  client_portal: "Client Portal",
  employee_portal: "Employee Portal",
  mobile: "Mobile App",
};

/** Human-readable action labels */
export const ACTION_LABELS: Record<string, string> = {
  view: "View",
  edit: "Edit",
  delete: "Delete",
  bypassAssignment: "Bypass Assignment",
  all: "All Clients",
  approve: "Approve",
  upload: "Upload",
  export: "Export",
  lock_period: "Lock Period",
  prepare: "Prepare",
  submit: "Submit",
  collect: "Collect",
  pay: "Pay",
  download: "Download",
  send: "Send",
  retry: "Retry",
  cancel: "Cancel",
  preview: "Preview",
  sync: "Sync",
  reply: "Reply",
  assign: "Assign",
  internal: "Internal Notes",
  go_live: "Go Live",
  reject: "Reject",
  registers: "Registers",
  filings: "Filings",
  create: "Create",
  validate: "Validate",
  authcode: "Auth Code",
  run: "Run",
  submit_rti: "Submit RTI",
  override: "Override",
  refund: "Refund",
  messages: "Messages",
  bookkeeping_approve: "Bookkeeping Approve",
};
