import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Search, RefreshCw, LayoutList, Columns3, CircleCheck, Clock3, AlertCircle, BriefcaseBusiness, Wallet, Files, Landmark, Building2, Receipt, Workflow, Plug } from 'lucide-react';
import { usePracticeOperations } from '@/hooks/usePracticeOperations';
import { useClientContext } from '@/contexts/ClientContext';
import { usePermissions } from '@/hooks/usePermissions';
import { isOpenOperation, operationHealth, type Operation } from '@/lib/practiceOperations';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';

const modules = [
  { title: 'Payroll & people', detail: 'Employers, pay runs and pensions', href: '/payroll', permission: 'payroll', icon: Wallet },
  { title: 'Accounts & review', detail: 'Evidence, working papers and sign-off', href: '/review-centre', permission: 'accounts', icon: Files },
  { title: 'Tax & compliance', detail: 'Returns, computations and obligations', href: '/corporation-tax', permission: 'accounts', icon: Landmark },
  { title: 'Bookkeeping', detail: 'Capture, categorise and reconcile', href: '/invoice-entry', permission: 'ledger', icon: Receipt },
  { title: 'Engagements', detail: 'Proposals, pricing and client billing', href: '/proposals', permission: 'billing', icon: BriefcaseBusiness },
  { title: 'Company secretarial', detail: 'Company records and filing workflows', href: '/secretarial', permission: 'secretarial', icon: Building2 },
  { title: 'Workflow automation', detail: 'Repeatable practice processes', href: '/practice/workflows', permission: 'automations', icon: Workflow },
  { title: 'Connections', detail: 'Manage your practice integrations', href: '/practice/integrations', permission: 'integrations', icon: Plug },
];
const tones = { red: 'bg-red-50 text-red-800 border-red-200 dark:bg-red-950 dark:text-red-200', amber: 'bg-amber-50 text-amber-800 border-amber-200 dark:bg-amber-950 dark:text-amber-200', green: 'bg-emerald-50 text-emerald-800 border-emerald-200 dark:bg-emerald-950 dark:text-emerald-200' };
const labels = { red: 'Needs attention', amber: 'Review next', green: 'On track' };
function HealthBadge({ row }: { row: Operation }) { const health = operationHealth(row); return <Badge variant="outline" className={tones[health]}>{labels[health]}</Badge>; }
function reason(row: Operation) {
  if (!isOpenOperation(row)) return 'This workflow is closed. Its status does not establish payment of any associated liability.';
  if (['failed','blocked','rejected'].includes(row.status)) return 'Resolve the reported failure or blocker in the source workspace before proceeding.';
  if (!row.dueDate) return 'No due date is recorded. Open the workspace to check the required next action.';
  return operationHealth(row) === 'red' ? 'The recorded date has passed and this workflow remains open. Check the source record and its acknowledgement.' : operationHealth(row) === 'amber' ? 'The recorded date is within seven days. Review outstanding preparation and approvals.' : 'The recorded date is more than seven days away. Continue preparation in the source workspace.';
}
export default function PracticeOperations() {
  const query = usePracticeOperations();
  const { selectedClientId, selectedClientName } = useClientContext();
  const { can } = usePermissions();
  const [search, setSearch] = useState('');
  const [health, setHealth] = useState('all');
  const [source, setSource] = useState('all');
  const [showClosed, setShowClosed] = useState(false);
  const [view, setView] = useState<'list' | 'board'>('list');
  const [selected, setSelected] = useState<Operation | null>(null);
  const rows = (query.data?.rows ?? []).filter(r => (!selectedClientId || r.clientId === selectedClientId) && (showClosed || isOpenOperation(r)));
  const filtered = rows.filter(r => (health === 'all' || operationHealth(r) === health) && (source === 'all' || source === r.source) && `${r.title} ${r.source} ${r.status}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => {
    const rank = { red: 0, amber: 1, green: 2 };
    return rank[operationHealth(a)] - rank[operationHealth(b)] || (a.dueDate ?? '9999').localeCompare(b.dueDate ?? '9999');
  });
  const clear = () => { setSearch(''); setHealth('all'); setSource('all'); setShowClosed(false); };
  return <div className="space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] font-semibold text-muted-foreground mb-2">Your practice, connected</p><h1 className="text-3xl md:text-4xl font-semibold tracking-tight">A clearer day ahead.</h1><p className="text-muted-foreground mt-3">{selectedClientName ? `Workspace for ${selectedClientName}` : 'The work that matters, across your practice.'}</p></div><div className="flex gap-2"><Button variant="outline" disabled={query.isFetching} onClick={() => query.refetch()}><RefreshCw className={`h-4 w-4 mr-2 ${query.isFetching ? 'animate-spin' : ''}`} />Refresh</Button>{can('clients','view') && <Button asChild><Link to="/clients">Client workspace <ArrowUpRight className="h-4 w-4 ml-2" /></Link></Button>}</div></header>
    <div className="grid gap-4 md:grid-cols-3">{(['red','amber','green'] as const).map(key => {
      const Icon = key === 'red' ? AlertCircle : key === 'amber' ? Clock3 : CircleCheck;
      return <button key={key} aria-pressed={health === key} onClick={() => setHealth(health === key ? 'all' : key)} className={`rounded-2xl border bg-card p-5 text-left transition hover:shadow-md focus-visible:ring-2 focus-visible:ring-ring ${health === key ? 'ring-2 ring-primary' : ''}`}><div className="flex items-center justify-between"><span className="font-medium text-sm">{labels[key]}</span><span className={`p-2 rounded-lg ${tones[key]}`}><Icon className="w-4 h-4" /></span></div><div className="text-4xl tracking-tight font-semibold mt-4 tabular-nums">{query.isLoading ? '—' : rows.filter(r => operationHealth(r) === key).length}</div><p className="text-xs text-muted-foreground mt-3">{key === 'red' ? 'Overdue, rejected or blocked' : key === 'amber' ? 'Due within 7 days or missing a date' : 'Future deadlines and completed work'}</p></button>;
    })}</div>
    {query.data?.errors.length > 0 && <div role="alert" className="rounded-lg border border-red-300 p-4">Unable to load: {query.data.errors.join(', ')}. Counts are incomplete. Refresh to retry.</div>}
    <section className="rounded-2xl border bg-card overflow-hidden" aria-label="Work queue">
      <div className="p-5 flex flex-wrap justify-between items-center gap-3"><div><h2 className="text-lg font-semibold">Your work queue <span className="ml-2 text-muted-foreground text-sm font-normal">{filtered.length} items</span></h2><p className="text-sm text-muted-foreground mt-1">Prioritised by urgency. Open an item to see the next step.</p></div><div className="flex rounded-lg border p-1 gap-1"><Button aria-label="List view" aria-pressed={view === 'list'} size="sm" variant={view === 'list' ? 'secondary' : 'ghost'} onClick={() => setView('list')}><LayoutList className="w-4 h-4" /></Button><Button aria-label="Board view" aria-pressed={view === 'board'} size="sm" variant={view === 'board' ? 'secondary' : 'ghost'} onClick={() => setView('board')}><Columns3 className="w-4 h-4" /></Button></div></div>
      <div className="border-y bg-muted/30 p-4 flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-48"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Search work queue" placeholder="Search your work…" className="pl-9 bg-card" value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label="Filter module" className="border rounded-lg bg-card text-sm p-2.5" value={source} onChange={e => setSource(e.target.value)}><option value="all">All modules</option>{Array.from(new Set(rows.map(r => r.source))).sort().map(s => <option key={s}>{s}</option>)}</select><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={showClosed} onChange={e => setShowClosed(e.target.checked)} />Completed</label><Button variant="ghost" size="sm" onClick={clear}>Reset filters</Button></div>
      {query.isLoading ? <div role="status" className="p-8 space-y-4">{[1,2,3].map(n => <div key={n} className="h-12 rounded-lg bg-muted animate-pulse" />)}<span className="sr-only">Loading authorised records</span></div> : filtered.length === 0 ? <div className="text-center py-14 px-5"><CircleCheck className="w-9 h-9 text-muted-foreground mx-auto mb-3" /><h3 className="font-semibold">No work in this view</h3><p className="text-sm text-muted-foreground mt-2">Try another filter or open a workspace below to prepare your next job.</p><Button variant="outline" className="mt-4" onClick={clear}>Clear filters</Button></div> : view === 'list' ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-muted-foreground text-xs"><tr className="border-b text-left"><th className="px-5 py-3">Work item</th><th className="p-3">Due date</th><th className="p-3">Workflow status</th><th className="p-3">Priority</th><th className="p-3"><span className="sr-only">Review</span></th></tr></thead><tbody>{filtered.map(row => <tr key={row.id} className="border-b last:border-0 hover:bg-muted/40"><td className="px-5 py-4"><button className="font-medium text-left hover:underline" onClick={() => setSelected(row)}>{row.title}</button><p className="text-xs text-muted-foreground mt-1">{row.source}</p></td><td className="p-3 whitespace-nowrap">{row.dueDate || 'Not set'}</td><td className="p-3 capitalize">{row.status.replace(/_/g,' ')}</td><td className="p-3"><HealthBadge row={row} /></td><td className="p-3"><Button variant="ghost" size="sm" aria-label={`Review ${row.title}`} onClick={() => setSelected(row)}><ArrowRight className="w-4 h-4" /></Button></td></tr>)}</tbody></table></div> : <div className="grid lg:grid-cols-3 gap-4 p-4 bg-muted/20">{(['red','amber','green'] as const).map(key => <section key={key} className="space-y-3"><h3 className="text-sm font-semibold px-1">{labels[key]} · {filtered.filter(r => operationHealth(r) === key).length}</h3>{filtered.filter(r => operationHealth(r) === key).map(row => <button key={row.id} className="w-full text-left p-4 rounded-xl border bg-card hover:border-primary shadow-sm" onClick={() => setSelected(row)}><p className="text-xs text-muted-foreground mb-2">{row.source}</p><p className="font-medium text-sm">{row.title}</p><div className="flex justify-between gap-2 mt-4 text-xs text-muted-foreground"><span>{row.dueDate || 'Date needed'}</span><span>{row.status.replace(/_/g,' ')}</span></div></button>)}</section>)}</div>}
      <div className="px-5 py-3 bg-muted/20 text-xs text-muted-foreground">Showing up to 500 records per authorised module. Submitted does not mean accepted; finalised does not mean paid.</div>
    </section>
    <section><div className="flex justify-between items-center mb-4"><h2 className="text-lg font-semibold">Your workspaces</h2><span className="text-xs text-muted-foreground">One practice. Connected workflows.</span></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{modules.filter(m => can(m.permission,'view')).map(({ title, detail, href, icon: Icon }) => <Link to={href} key={title} className="group rounded-xl border bg-card p-5 transition hover:shadow-md hover:border-primary/30"><div className="flex justify-between"><Icon className="h-5 w-5 text-muted-foreground" /><ArrowUpRight className="h-4 w-4 text-muted-foreground group-hover:text-foreground" /></div><h3 className="font-semibold text-sm mt-4">{title}</h3><p className="text-xs text-muted-foreground leading-relaxed mt-2">{detail}</p></Link>)}</div></section>
    <Sheet open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><SheetContent className="sm:max-w-lg overflow-y-auto">{selected && <><SheetHeader><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{selected.source}</p><SheetTitle className="text-2xl leading-tight">{selected.title}</SheetTitle><SheetDescription>Review the context before opening the source workspace.</SheetDescription></SheetHeader><div className="space-y-6 mt-7"><HealthBadge row={selected} /><dl className="grid grid-cols-2 gap-4 rounded-xl bg-muted/40 p-4 text-sm"><div><dt className="text-muted-foreground">Workflow status</dt><dd className="font-medium mt-1 capitalize">{selected.status.replace(/_/g,' ')}</dd></div><div><dt className="text-muted-foreground">Recorded date</dt><dd className="font-medium mt-1">{selected.dueDate || 'Not set'}</dd></div></dl><div><h3 className="font-semibold">Recommended next step</h3><p className="text-sm text-muted-foreground leading-relaxed mt-2">{reason(selected)}</p></div><Button asChild className="w-full"><Link to={selected.href}>Open {selected.source.toLowerCase()} workspace <ArrowRight className="h-4 w-4 ml-2" /></Link></Button><p className="text-xs text-muted-foreground">Priority is based on recorded status and dates. It does not validate a tax calculation or confirm a payment.</p></div></>}</SheetContent></Sheet>
  </div>;
}
